version: "3"

services:
  api:
    build: .
    container_name: nestjs-api
    env_file:
      - ./.docker.env
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
      - redis

  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      # - 27020:27017
    volumes:
      - mongodb_volume:/data/db

  redis: 
    container_name: redis_db
    image: redis:6-alpine
    ports:
      # - 6379:6379
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
  mongodb_volume: